version: '2'

networks:
  default:

services:
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "5984:5984"
    networks:
      - default

  peer0.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb0

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "6984:5984"
    networks:
      - default

  peer1.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb1

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "7984:5984"
    networks:
      - default

  peer0.org2.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb2

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "8984:5984"
    networks:
      - default

  peer1.org2.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb3

  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "9984:5984"
    networks:
      - default

  peer0.org3.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb4

  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "10984:5984"
    networks:
      - default

  peer1.org3.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb5

  couchdb6:
    container_name: couchdb6
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "11984:5984"
    networks:
      - default

  peer0.org4.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb6:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb6

  couchdb7:
    container_name: couchdb7
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "12984:5984"
    networks:
      - default

  peer1.org4.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb7:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb7

#   couchdb8:
#     container_name: couchdb8
#     image: hyperledger/fabric-couchdb
#     environment:
#       - COUCHDB_USER=
#       - COUCHDB_PASSWORD=
#     ports:
#       - "13084:5984"
#     networks:
#       - default

#   peer0.org5.example.com:
#     environment:
#       - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
#     depends_on:
#       - couchdb8

#   couchdb9:
#     container_name: couchdb9
#     image: hyperledger/fabric-couchdb
#     environment:
#       - COUCHDB_USER=
#       - COUCHDB_PASSWORD=
#     ports:
#       - "14084:5984"
#     networks:
#       - default

#   peer1.org5.example.com:
#     environment:
#       - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
#     depends_on:
#       - couchdb9

#   couchdb10:
#     container_name: couchdb10
#     image: hyperledger/fabric-couchdb
#     environment:
#       - COUCHDB_USER=
#       - COUCHDB_PASSWORD=
#     ports:
#       - "15084:5984"
#     networks:
#       - default

#   peer0.org6.example.com:
#     environment:
#       - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
#     depends_on:
#       - couchdb10

#   couchdb11:
#     container_name: couchdb11
#     image: hyperledger/fabric-couchdb
#     environment:
#       - COUCHDB_USER=
#       - COUCHDB_PASSWORD=
#     ports:
#       - "16084:5984"
#     networks:
#       - default

#   peer1.org6.example.com:
#     environment:
#       - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
#     depends_on:
#       - couchdb11
